# https://github.com/expo/expo-github-action/tree/main/preview-comment#publish-and-preview-on-pull-request
name: "Build Expo Storybook for PR"
on:
  pull_request:
env:
  EXPO_PUBLIC_STORYBOOK_ENABLED: true
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  preview:
    needs: tests
    permissions:
      contents: read
      pull-requests: write # Allow comments on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        id: checksecrets
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ "$EXPO_TOKEN" == "" ]; then
            echo "secretspresent=NO" >> $GITHUB_OUTPUT
          else
            echo "secretspreseng=YES" >> $GITHUB_OUTPUT
          fi
      - name: ğŸ— Setup repo
        if: (steps.checksecrets.outputs.secretspresent == 'YES')
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        if: (steps.checksecrets.outputs.secretspresent == 'YES')
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: ğŸ— Setup EAS
        if: (steps.checksecrets.outputs.secretspresent == 'YES')
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        if: (steps.checksecrets.outputs.secretspresent == 'YES')
        run: yarn install

      - name: ğŸš€ Create preview
        if: (steps.checksecrets.outputs.secretspresent == 'YES')
        id: preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch=pr-${{ github.event.number }}-storybook
          comment: false

      - name: Comment PR
        if: (steps.checksecrets.outputs.secretspresent == 'YES')
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: preview-storybook-build
          message: |
            ğŸ““ **Storybook** [preview update](${{ steps.preview.outputs.link }}) is ready for use with [Expo Go](https://expo.dev/expo-go):

            <a href="${{ steps.preview.outputs.link }}"><img src="${{ steps.preview.outputs.qr }}" width="250px" height="250px" /></a>
